spring.application.name=inventory-service
server.port=8083

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://[IP_ADDRESS]/exampledb
spring.datasource.username=exampleuser
spring.datasource.password=examplepassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
