spring.application.name=inventory-service
server.port=8083

# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://[IP_ADDRESS]/exampledb
spring.datasource.username=exampleuser
spring.datasource.password=examplepassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka Configuration Example
spring.kafka.bootstrap-servers=example-kafka.aivencloud.com:18964
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-512
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="exampleuser" password="examplepassword";
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.location=src/main/resources/ca.pem

# Consumer Configuration (Topic lắng nghe từ Order Service)
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
app.kafka.topics.listen=order-events

# Producer Configuration (Topic phát mặc định kết quả kho)
spring.kafka.template.default-topic=fulfillment-events
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
app.kafka.topics.publish=fulfillment-events
