<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>QuickBite.Identity</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickBite.Identity.Domain\QuickBite.Identity.Domain.csproj" />
    <ProjectReference Include="..\QuickBite.Identity.Application.Contracts\QuickBite.Identity.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.0.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.0.0" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.0.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.0.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.0.0" />
  </ItemGroup>

</Project>
